# Create environment:
#   conda env create --file environment.yml
# Remove environment:
#   conda remove --name bioai --all

name: bioai

channels:
  - defaults
  - conda-forge

dependencies:
  - python>=3.11
  - pip
  - cython

  # Standard scientific Python
  - numpy
  - matplotlib
  - scipy<=1.12.0
  - pandas
  - mpi4py
  #- conda-forge::pymc

  - pip:

    # Code quality
    - pre-commit
    - black
    - isort
    - ruff
    - pytest

    # Plotting
    - seaborn
    - arviz

    # Jupyter
    - jupyterlab
    - notebook
    - jupyter-book
    - jupytext
    - "rich[jupyter]"

    # SciKit
    - scikit-learn
    - scikit-image

    # JAX ecosystem
    - "jax[cpu]"
    - jaxlib
    - jaxtyping
    - chex
    - flax
    - equinox
    - jaxopt
    - optax
    - distrax
    - blackjax
    #- numpyro
    - clu

    #  PyTorch ecosystem
    - torch
    - torchvision
    - torchaudio
    #- pyro-ppl

    # Tensorflow ecosystem
    - tensorflow
    - tensorflow_datasets

    # Cross-ecosystem
    - einops

    # Misc.
    - h5py
    - tqdm
